services:
  benchmark-app:
    build:
      context: .
      network: host
    image: tfm-benchmark-app:latest
    container_name: benchmark-app
    network_mode: host
    environment:
      # Al usar red host, se conecta a Mongo a través de localhost
      - MONGO_URL=mongodb://127.0.0.1:27017
      - MONGO_DB=benchmarks
      - BENCHMARK_DISK_PATH=/tmp/benchmark
    depends_on:
      - mongo
    volumes:
      - benchmark-tmp:/tmp/benchmark
      - /etc/os-release:/host/etc/os-release:ro
    privileged: true
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: benchmark-mongo
    network_mode: host
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
  benchmark-tmp:
